USERNAME = 'admin'
PASSWORD = 'n3wenginelinta5'
SECRET = 'II*^WvQiOkv)QihQwQZ<JH!YY/q)v%TY'
APP_NAME = 'LINTAS ENGINE CONSOLE'
APP_ROOT_DIR = "/var/www/crawler-engine"
# APP_ROOT_DIR = "/opt/engine.lintas.me"
CONSOLE_ROOT_DIR = "%s/webapp" % APP_ROOT_DIR
DB_PATH = "%s/db/engine.json" % CONSOLE_ROOT_DIR
CONFIG_PATH = "/opt/crawler"
